spring.application.name=gestao-custos

#Postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/meu_projeto
spring.datasource.username=postgres
spring.datasource.password=2a6e005d7f
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true